Fixed a compatibility issue in the plotting tool that could cause the plotting tool to fail with the error "AttributeError: 'module' object has no attribute '_cmapnames'" in some cases.  Many thanks to Ryuichi Arafune (from MANA and NIMS) and C.H. Lee (from the National Cheng-Chi University, Taiwan), for having contacted me about this problem. Special thanks to Ryuichi Arafune, for suggesting a solution.